---
- name: manage ec2
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: skip unmanaged hosts
      meta: end_host
      when: hostvars[aws_ec2_inventory].tags.Managed | default("False") != "True"

    - name: skip hosts that doesnt have my name
      meta: end_host
      when: "'yuvaly' not in hostvars[aws_ec2_inventory].tags.Name | default('')"

  roles:
    - role: hostname
    - role: service
    - role: restart
